/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ITasks = t.iface([], {
  "id": t.opt("string"),
  "userId": t.opt("string"),
  "name": "any",
  "date": "object",
  "description": "string",
  "location": "string",
  "stopped": "boolean",
});

export const exportedTypeSuite: t.ITypeSuite = {
  ITasks,
};
export default exportedTypeSuite;
